version: 2.1

jobs:
  build:
    docker:
      - image: integromat/circleci-docker
    working_directory: /workspace/make-web
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Create .env file from Context
          command: | 
            env | grep -e ^NEXT_ > .env
            env | grep -e ^CONTENTFUL_ >> .env
      - run:
          name: Docker Image Build
          command: |
            BASE_BRANCH=$([[ $CIRCLE_BRANCH =~ master|^v[[:digit:]]+ ]] && echo "master" || echo "dev")
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
            DOCKER_BUILDKIT=1 docker build --build-arg BUILDKIT_INLINE_CACHE=1 --progress=plain -t "integromat/make-web:${CIRCLE_BRANCH}" --build-arg BUILD_BRANCH="$CIRCLE_BRANCH" --build-arg BASE_BRANCH="$BASE_BRANCH" --build-arg NPM_TOKEN="$NPM_TOKEN" .
      - deploy:
          name: Push to DockerHub
          command: |
            docker push "integromat/make-web:${CIRCLE_BRANCH}"

  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run:
          name: Notify control server
          command: bash <(curl --silent --location --insecure --user "${NOTIFY_USER}:${NOTIFY_PASSWORD}" 'https://control.integromat.cloud:8443/circleci_notify.sh')
          no_output_timeout: 60m

workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - org-default
            - make-web
      - notify:
          context: org-default
