export const APPS_COLLECTION_ARRAY = [
    'Google Sheets',
    'Gmail',
    'Google Drive',
    'Airtable',
    'Slack',
    'Telegram Bot',
    'Google Calendar',
    'Facebook Lead Ads',
    'Google Docs',
    'WooCommerce',
    'Dropbox',
    'Facebook Pages',
    'Microsoft 365 Email',
    'Mailchimp',
    'HubSpot CRM',
    'Discord',
    'Trello',
    'Google Forms',
    'Shopify',
    'Twitter',
    'Monday',
    'Pipedrive CRM',
    'Stripe',
    'ActiveCampaign',
    'ClickUp',
    'WordPress',
    'Twilio',
    'Notion',
    'Google Contacts',
    'Calendly',
    'Microsoft 365 Excel',
    'Typeform',
    'Jotform',
    'Webflow',
    'MySQL',
    'CloudConvert',
    'SendGrid',
    'Asana',
    'Sendinblue',
    'Salesforce',
    'Zoom',
    'Bitly',
    'Instagram for Business',
    'LinkedIn',
    'Xero',
    'Manychat',
    'QuickBooks',
    'OneDrive',
    'Facebook Groups',
    'Google Analytics',
    'Survey123',
    'Todoist',
    'Zoho CRM',
    'Zapier',
    'Microsoft Word Templates',
    'Google Maps',
    'AWS S3',
    'MailerLite Classic',
    'Jira Cloud Platform',
    'Facebook Conversions API',
    'Zendesk',
    'Google Slides',
    'Cognito Forms',
    'Blogger',
    'PDF.co',
    'PayPal',
    'HTML/CSS to Image',
    'Gravity Forms',
    'Facebook Custom Audiences',
    'Instagram',
    'Microsoft 365 Calendar',
    'Toggl Track',
    'Bubble',
    'Facebook Insights',
    'Klaviyo',
    'ClickSend SMS',
    'Facebook Messenger',
    'Eledo PDF',
    'Microsoft SQL Server',
    'Mailgun',
    'Google Chrome',
    'LINE',
    'PostgreSQL',
    'Google Cloud Vision',
    'Evernote',
    'Kommo',
    'Knack',
    'Microsoft Teams',
    'Buffer',
    'Google Tasks',
    'Freshdesk',
    'Ninox',
    'Acuity Scheduling',
    'Google Chat',
    'BigQuery',
    'Github',
    'Google Translate',
    'reddit',
    'Microsoft SharePoint Online',
    'ClickFunnels',
    'DocuSign',
    'Spotify',
    'PandaDoc',
    'Zoho Mail',
    'Contact Form 7',
    'Etsy',
    'Intercom',
    'Facebook',
    'Rav Messer / Responder',
    'Facebook Offline Conversions',
    'Clockify',
    'IFTTT',
    'PrestaShop',
    'Google Data Studio',
    'Chatfuel',
    'Pocket',
    'Coda',
    'Phantombuster',
    'Podio',
    'Keap',
    'ShipStation',
    'Smoove',
    'Tumblr',
    'SendPulse',
    'PDFMonkey',
    'HighLevel',
    'Rebrandly',
    'Google Workspace Admin',
    'Microsoft To Do',
    'Short.io',
    'Wix',
    'Box',
    'Pipefy',
    'Adalo',
    'Apify',
    'RD Station',
    'Wave',
    'Google My Business',
    'Fakturoid',
    'Eventbrite',
    'MongoDB',
    'GetResponse',
    'Mautic',
    'RingCentral',
    'Memberstack',
    'lemlist',
    'GitLab',
    'LinkedIn Lead Gen Forms',
    'Zoho Books',
    'Square',
    'Smartsheet',
    'Harvest',
    'Vtiger CRM',
    'Google Cloud Storage',
    'Unbounce',
    'Freshworks CRM',
    'Google Photos',
    'Adobe Commerce',
    'Google Cloud Firestore',
    'Fio banka',
    'APITemplate.io',
    'Beds24',
    'Pushbullet',
    'Vimeo',
    'ConvertKit',
    'RAYNET CRM',
    'AWeber',
    'OpenWeatherMap',
    'ActiveTrail',
    'Amazon Lambda',
    'Bannerbear',
    'Chargebee',
    'Close CRM',
    'Paperform',
    'mailparser.io',
    'Databox',
    'WebinarJam',
    'Docparser',
    'Drip',
    'Zoho Forms',
    'Teamwork',
    'TikTok',
    'Tally',
    'Bitrix24',
    'PrintNode',
    'Twitch',
    'EverWebinar',
    'Foursquare',
    'Wild Apricot',
    'Google Groups',
    'MessageBird',
    'Aircall',
    'Invoice Ninja',
    'Postmark',
    'Mailjet',
    'Microsoft 365 People',
    'eSignatures.io',
    'Google Cloud Speech',
    'Survey Monkey',
    'Help Scout',
    'OneSignal',
    'Tripetto',
    'Feedly',
    'Cloudinary',
    'Docupilot',
    'Front',
    'ImgBB',
    'Mixpanel',
    'Zoho Creator',
    'pdfFiller',
    'WP Webhooks',
    'SuiteCRM 7/SugarCRM 6 CE',
    'Zoho Invoice',
    '1SaaS.co',
    'Wrike',
    'Basecamp 3',
    'ZeroBounce',
    'Squarespace',
    'Google Ads Campaign Management',
    'OneNote',
    'SuperSaaS',
    'Zoho Desk',
    'Constant Contact',
    'GatewayAPI SMS',
    'Google Ads Lead Forms',
    'Flashyapp',
    'Sendy',
    'iDoklad',
    'Strava',
    'GIPHY',
    'Segment',
    'Streak',
    'lexoffice',
    'Formstack',
    'Clearbit',
    'ScheduleOnce',
    'Teamleader',
    'ABRA FlexiBee',
    'ConvertAPI',
    'ParseHub',
    'Plivo',
    'Wufoo',
    'BulkGate',
    'Formstack Documents',
    'Microsoft Power BI',
    'Skype',
    'SmartEmailing',
    'ThriveCart',
    'Bitbucket',
    'Qonto',
    'Amazon SES',
    'Google Cloud Dialogflow ES',
    'Cloudflare',
    'Customer.io',
    'Mattermost',
    'Poptin',
    'Thinkific',
    'WhatsApp Business Cloud',
    'Zoho Inventory',
    'Facebook Ads Campaign Management',
    'tawk.to',
    'Firebase Cloud Messaging',
    'NeverBounce',
    'Snov.io',
    'Google Ads Conversions',
    'ArcGIS Field Maps',
    'CoinMarketCap',
    'Google Ads Customer Match',
    'JustCall',
    'Campaign Monitor',
    'Glide',
    'Plutio',
    'Snowflake',
    'Chatforma',
    'MeisterTask',
    'WPForms',
    'Zoho Projects',
    'CraftMyPDF.com',
    'Ghost',
    'GoSMS',
    'Hunter',
    'Mustache',
    'OneSimpleApi',
    'Revolut Business',
    'Circle',
    'Copper',
    'Dux-Soup',
    'Ecomail.cz',
    'Zoho Sign',
    'Autopilot',
    'Hootsuite',
    'Hotmart',
    'Miro',
    'Patreon',
    'Sendcloud',
    'InforUMobile',
    'Magento 1 (deprecated)',
    'Teachable',
    'BambooHR',
    'DeepL',
    'NinjaForms',
    'SoundCloud',
    'Tadabase',
    'AfterShip',
    'Google Cloud Text-to-Speech',
    'Kartra',
    'MailerSend',
    'SendFox',
    'Shortcuts',
    'VideoAsk',
    'SignRequest',
    'FreshBooks',
    'Geckoboard',
    'Numverify',
    'Odoo',
    'Pushover',
    'QuickCapture',
    'Chatwork',
    'Flickr',
    'Landbot',
    'PDF4me',
    'Pushcut',
    'Remove.bg',
    'Shotstack',
    'Capsule CRM',
    'Crisp',
    'Inoreader',
    'Skloňování Jmen',
    'ChatGuru',
    'Habitica',
    'Medium',
    'REST Countries',
    'TextMagic',
    'VK.com',
    'Zoho Campaigns',
    'eversign',
    'Caflou',
    'Clio Manage',
    'Follow Up Boss',
    'Google Natural Language',
    'Moosend',
    'Omnisend',
    'Zendesk Guide',
    'Agile CRM',
    'Amazon Redshift',
    'EspoCRM',
    'Placid',
    'Process Street',
    'YouCanBook.me',
    'Bigin by Zoho CRM',
    'FAPI',
    'Livestorm',
    'Merk',
    'Moneybird',
    'Nextcloud',
    'Sellsy',
    'Swipe Pages',
    'Tabidoo',
    'Woodpecker',
    'YNAB',
    'D7SMS',
    'Google Meet',
    'Insightly CRM',
    'Ontraport',
    'ScrapingBee',
    'Směnné kurzy ČNB',
    'Tny',
    'iLovePDF',
    'Rocket.Chat',
    'CloudTalk',
    'Google Shopping',
    'Planfix',
    'Powerlink',
    'Twist',
    'Disqus',
    'Elastic Email',
    'EmailOctopus',
    'Fibery',
    'Freshservice',
    'JivoChat',
    'Loyverse',
    'Netlify',
    'PDF Generator API',
    'Rossum',
    'Xama Onboarding',
    'AppSheet',
    'Burst SMS',
    'Caspio',
    'ChartMogul',
    'Egnyte',
    'Figma',
    'Lob',
    'PagerDuty',
    'Plotly',
    'Prospero',
    'Unsplash',
    'UpViral',
    'signNow',
    'Alegra',
    'Binance',
    'CallRail',
    'Citrix ShareFile',
    'Discourse',
    'Formidable Forms',
    'QuickBooks Time',
    'StealthSeminar',
    'Superfaktura',
    'Teamwork Desk',
    '123FormBuilder',
    'Apple Push Notifications',
    'Deputy',
    'Hubstaff',
    'Pointerpro',
    'Reply.io',
    'SharpSpring',
    'Stackby',
    'noCRM.io',
    'Abyssale',
    'Canny',
    'ChytryStart',
    'Dialpad',
    'Kintone',
    'Mallabe Images',
    'MonkeyLearn',
    'Productboard',
    'sms77.io',
    'Clearout',
    'Demio',
    'Google Cloud Pub/Sub',
    'LearnDash',
    'Salesmate',
    'Thanks.io',
    'Zoho Recruit',
    'bexio',
    'DigitalOcean Spaces',
    'Komerční banka',
    'MOCO',
    'Mailchimp Transactional Email',
    'Raindrop.io',
    'Razorpay',
    'ServiceM8',
    'Splitwise',
    'Wasabi',
    'Wistia',
    'Asaas',
    'Bolt IoT',
    'Encharge',
    'EngageBay',
    'Everhour',
    'Frame.io',
    'Freshping',
    'Infobip',
    'Microsoft 365 Planner',
    'Outseta',
    'RescueTime',
    'Respond.io',
    'Runkeeper',
    'SeaTable',
    'Semrush',
    'Slybroadcast',
    'Tapfiliate',
    'Waze Deep Links',
    'Zammad',
    'BaseLinker',
    'BotStar',
    'FastField',
    'Formsite',
    'GetAccept',
    'Handwrytten',
    'LinkedIn Matched Audiences',
    'Mallabe Currencies',
    'Opsgenie',
    'Softr',
    'Survicate',
    'TalentLMS',
    'Tookan',
    'Uploadcare',
    'ViewDNS',
    'Viral Loops',
    'pCloud',
    'AidaForm',
    'BigMarker',
    'Delighted',
    'Documint',
    'Elasticsearch',
    'GetMyInvoices',
    'GoToWebinar',
    'Kanbanize',
    'Leady',
    'Onfleet',
    'Pivotal Tracker',
    'Reamaze',
    'SMSAPI',
    'Shortcut',
    'StackExchange',
    'TimeCamp',
    'UNISENDER',
    'Yodel.io',
    'ZapSign',
    'Action Network',
    'Beeminder',
    'ChatBot',
    'Cloudmersive',
    'Datadog',
    'Easyship',
    'LinkedIn Ads Campaign Management',
    'LionDesk',
    'LiveWebinar',
    'Maropost Commerce Cloud',
    'Mavenlink',
    'OfficeGuy/SUMIT',
    'PomoDoneApp',
    'Printful',
    'RabbitMQ',
    'SMS Alert',
    'Salesflare',
    'SendOwl',
    'SparkPost',
    'Steam',
    'Techulus Push',
    'Ticket Tailor',
    'Trakt',
    'Trustpilot',
    'Twilio Verify',
    'Vyfakturuj.cz',
    'allmysms',
    'Apollo',
    'ArtiBot.ai',
    'BeLazy',
    'BizMachine',
    'Cisco Webex',
    'Contacts+',
    'EasyCSV',
    'Email List Verify',
    'Freshchat',
    'HappyForms',
    'Katana',
    'Landingi',
    'MailboxValidator',
    'Mailrelay',
    'Okta',
    'Parseur',
    'People Data Labs',
    'Pingdom',
    'Platformly',
    'Recruitee',
    'Recurly',
    'Redmine',
    'SignalWire',
    'SugarCRM 7/8',
    'Toodledo',
    'Transloadit',
    'UPS Quantum View',
    'Vybit Notifications',
    'Zamzar',
    'iÚčto.cz',
    'BoondManager',
    'Clickatell',
    'Cliengo',
    'Fomo',
    'Instapage',
    'LiveAgent',
    'Nexweave',
    'Pagar.me',
    'PhoneBurner',
    'ProfitWell',
    'Quentn',
    'ReceitaWS',
    'Signi',
    'The Keys Pro',
    'Veriphone',
    'Wappalyzer',
    'YOURLS',
    'Anabix CRM',
    'Apple Map Links',
    'Appointlet',
    'Basin',
    'Bouncer',
    'BugHerd',
    'Cloud BOT',
    'Convertio',
    'Converts.online',
    'CraftQL',
    'Custom JS',
    'DEAR Inventory',
    'Dynalist',
    'E-goi',
    'Exact Spotter V2',
    'Freshmarketer',
    'Iterable',
    'LinkedIn Ads Reports',
    'Moskit CRM',
    'NeoGate',
    'Parsio',
    'Phaxio',
    'RepairShopr',
    'Simpleen Translation',
    'SurveySparrow',
    'Syncro',
    'TRIGGERcmd',
    'Tableau',
    'Textbelt',
    'Textline',
    'Z-API',
    'Zendesk Sunshine',
    'codeREADr',
    'involve.me',
    '4leads',
    'Amazing Marvin',
    'ApuTime',
    'Beaconstac',
    'ChargeOver',
    'CleverReach',
    'ClickMeeting',
    'ConvertBox',
    'Cuttly',
    'Cyfe',
    'Drupal',
    'E-conomic',
    'EasyPost',
    'Facebook Catalogs',
    'Files.com',
    'FreeAgent',
    'FreeFinance',
    'Getform',
    'Gist',
    'Gumroad',
    'IPQualityScore',
    'Judge.me',
    'Keboola',
    'Kickbox',
    'Linear',
    'MEETOVO',
    'OfficeRnD',
    'Outgrow',
    'Paymo',
    'Printavo',
    'Quotient',
    'RenderForm',
    'Robolytix',
    'SALESmanago',
    'Simpleshop.cz',
    'Simvoly',
    'Site24x7',
    'TMetric',
    'Thankster',
    'Timeular',
    'UseINBOX',
    'Virtuagym',
    'Zoho People',
    'elopage',
    '1CRM',
    'Aspose',
    'Braintree',
    'Clust',
    'Convercus Loyalty',
    'DHL',
    'DeBounce',
    'Digistore24',
    'Drift',
    'Dropcontact',
    'Gitter',
    'Go4Clients',
    'GoCanvas',
    'GrowSurf',
    'HappyFox Help Desk',
    'IPEX',
    'KanbanFlow',
    'Mail Komplet',
    'MailBluster',
    'MemberVault',
    'MinuteMerge',
    'Mitto SMS',
    'New Relic',
    'Pipedrive Resellers Portal',
    'Placetel',
    'Pointagram',
    'Quaderno',
    'ReferralHero',
    'Resource Guru',
    'Review Scraper',
    'SigParser',
    'SingleCase',
    'Swapcard',
    'Taphome',
    'Toky',
    'Vonage',
    'Webex Meetings',
    'Woobox',
    'Yandex.Translate',
    'Zoho Writer',
    'dotdigital',
    'uProc',
    'AX Semantics',
    'AmeriCommerce',
    'Axonaut',
    'Betty Blocks',
    'BlockSurvey',
    'Byteplant Address Validator',
    'Clientjoy',
    'Clover POS',
    'Cloze',
    'Deskera',
    'DocuWare',
    'EasyWeek',
    'Emma',
    'Endorsal',
    'Expensify',
    'FareHarbor',
    'FireText',
    'Flow XO',
    'Focuster',
    'Ganttic',
    'Gfycat GIF Hosting',
    'GoToMeeting',
    'GroupMe',
    'Hive',
    'LastPass',
    'MSG91',
    'MailerCheck',
    'Myphoner',
    'Nimble',
    'OpenGraph.io',
    'Plex',
    'Quanda',
    'Qwilr',
    'Rudderstack',
    'SIGNL4',
    'SMSFactor',
    'Sendlane',
    'SerwerSMS',
    'Shipday',
    'Signable',
    'Smaily',
    'SolarWinds Service Desk',
    'Sonar',
    'Timely',
    'Traction Tools',
    'Transistor.fm',
    'TrueMail',
    'Urban Dictionary',
    'User.com',
    'Wealthbox',
    'Wootric',
    'Yelp',
    'coreBos',
    'iAuditor',
    'sendSMS',
    'wflow.com',
    '2all CMS',
    'ADManager Plus',
    'Adobe Acrobat Sign',
    'Aha!',
    'Airmeet',
    'Amazon SNS',
    'Auth0',
    'Backendless',
    'BigMailer',
    'Botsify',
    'Brave',
    'CS-Cart',
    'Canvas LMS',
    'Clicksign',
    'Datagma',
    'Daylite',
    'Detrack',
    'Domotron control',
    'Dubb',
    'Easy Project',
    'Edusign',
    'Factorial',
    'Favro',
    'Float',
    'Global SMS',
    'Jitbit',
    'KissFlow',
    'Kixie',
    'Klenty',
    'Mailercloud',
    'Mailigen',
    'MaintainX',
    'MemberPress',
    'Missive',
    'Mixmax',
    'Mocean',
    'Odyssee Field Service',
    'Orbit',
    'PHP Point of Sale',
    'Plug&Paid',
    'Proofly',
    'Qualtrics',
    'Quickbase',
    'QuintaDB',
    'Relatel',
    'SMSC',
    'ScanOrders',
    'Seliom',
    'Senuto',
    'Shift4Shop',
    'Simplero',
    'SmartTask',
    'Stamped.io',
    'Tiflux',
    'Timing',
    'Trint',
    'Typebot',
    'Userback',
    'VdoCipher',
    'Vertical Response',
    'WhatConverts',
    'When I Work',
    'Wishpond',
    'Zendesk Sell',
    'Zenler',
    'Zoho Sheet',
    'awork',
    'kutt',
    'Active Directory',
    'Acuity PPM',
    'AdRoll',
    'Atera',
    'Attendance GIRITON',
    'Award Force',
    'Basecamp 2',
    'BlueLink',
    'Bonusly',
    'Booqable',
    'Borisbot',
    'Botsheets',
    'Businesslogic.online',
    'Byteplant Email Validator',
    'Byteplant Phone Validator',
    'CallTrackingMetrics',
    'Cflow',
    'Chatra',
    'Crocoblock',
    'Customerly',
    'DigiSign',
    'Dribbble',
    'EET',
    'Ecologi',
    'Evolio',
    'Filestack',
    'Fireflies.ai',
    'Fleep',
    'Global Payments WebPay',
    'Gmelius',
    'GoShop',
    'GoodBarber',
    'GoodBarber eCommerce',
    'Groove',
    'HelloSign',
    'Helpwise',
    'HeySummit',
    'Image-Charts',
    'Initiative CRM',
    'Jenkins',
    'JobNimbus',
    'KiyOh',
    'LinkedIn Lead Gen Forms - Events',
    'LiquidPlanner',
    'Magentrix',
    'Mailcheck',
    'Meero',
    'Memberful',
    'NeonCRM',
    'NetHunt',
    'Noticeable',
    'Nusii',
    'Nutshell',
    'Néctar CRM',
    'Obras Online',
    'Olark',
    'Optimy',
    'Order Desk',
    'People HR',
    'Pneumatic',
    'PushEngage',
    'Pushwoosh',
    'QuickFile',
    'Runo Call Management CRM',
    'Ryver',
    'SMS Niaga',
    'SMSEdge',
    'SMSzasilam',
    'SMTP2GO',
    'Salla',
    'Scrive eSign',
    'Sentry',
    'Service Provider Pro',
    'SilFer Bots',
    'Site Search 360',
    'Status Hero',
    'Stencil',
    'TeamWave',
    'Teamup',
    'The Keys',
    'UniOne',
    'UnionBank',
    'Unleashed Software',
    'VBOUT',
    'Vidalytics',
    'WeChat Official Account',
    'WeSupply',
    'Weekdone',
    'WiserNotify',
    'WordsAPI',
    'Zonka Feedback',
    'linkish.io',
    'timeBuzzer',
    'ČVUT KOS',
    '10to8',
    '1net CRM',
    '29 Next',
    '602 Sofa',
    '8x8',
    'A&A/FITPASS Calltracking',
    'Abby',
    'Accelo',
    'ActiveDEMAND',
    'AddMe Reviews',
    'Agendor',
    'AgilePlace',
    'Alexa Internet',
    'Amplitude',
    'Android',
    'AnnounceKit',
    'Apolearn LMS',
    'Apple Safari',
    'Apple iOS',
    'ApptiveGrid',
    'Archive',
    'Arduino',
    'Arlo',
    'Atarim',
    'Attio',
    'Authvia',
    'Autoklose',
    'Automation Anywhere (Cloud)',
    'Automizy',
    'Avaza',
    'Avochato',
    'Axiom',
    'Bambuser',
    'Banqup',
    'Barcodes',
    'Baserow',
    'Beamer',
    'Becon',
    'Behavior Sales',
    'Bellbird',
    'Bidsketch',
    'Big Cartel',
    'BigML',
    'Billit',
    'Billsby',
    'Bind ERP',
    'Bing Spell Check',
    'Bitskout',
    'Blink',
    'Book Like A Boss',
    'Bookafy',
    'Boost Note',
    'Breeze',
    'BringData.co',
    'Browse AI',
    'Bullet',
    'CDP & CRM CareCloud',
    'COVID-19',
    'CSV',
    'California Bank & Trust',
    'Call Assist',
    'CallHippo',
    'Callingly',
    'Candu',
    'Captain Data',
    'Captivate',
    'Celestory',
    'Celoxis',
    'Channels',
    'Checkvist',
    'Chiavistello',
    'Cin7',
    'Citibank',
    'Clever Messenger',
    'Clicfans',
    'Cloudpress',
    'Coassemble',
    'Colligso TextIn',
    'Colligso WalletIn',
    'Comeet',
    'CommCare',
    'CommerceHQ',
    'CompanyHub',
    'Confection',
    'Corsizio',
    'Corymbus',
    'Costbucket',
    'Coupa',
    'Coveo',
    'CrowdPower',
    'Crowdin',
    'Currency',
    'Custify',
    'Cuttly Team',
    'Data store',
    'Data24-7',
    'Datelist',
    'Deezer',
    'Delesign',
    'Demodesk',
    'Dext',
    'Diabolocom',
    'Diigo',
    'Disparo Pro',
    'Document360',
    'Dokan',
    'Dootax',
    'DropFunnels',
    'EZOfficeInventory',
    'Earned Value',
    'Easelly',
    'Eden AI',
    'Elementor',
    'Elite Seller',
    'Email',
    'Emailkampane.cz',
    'Emercury',
    'Emporix Commerce',
    'Encryptor',
    'Engage',
    'Experian Aperture',
    'FAPI Member',
    'FTP',
    'Fatture in Cloud',
    'FaunaDB',
    'Feedier',
    'Fidoo',
    'FileCloud',
    'Filestage',
    'Finolog',
    'Flexie CRM',
    'Flock',
    'Flow Control',
    'FluentCRM',
    'Flutterwave',
    'FogBugz',
    'Folderit DMS',
    'ForceManager',
    'FormCrafts',
    'Formaloo',
    'Formspree',
    'Fortnox',
    'FreeScout',
    'Freedcamp',
    'Freelo',
    'Fresh Proposals',
    'Freshmail',
    'Fulcrum',
    'GPS Tools',
    'GakuNin RDM',
    'GanttPRO',
    'GatherContent',
    'GenerateBanners.com',
    'GetProspect',
    'Gifda',
    'Gigrove',
    'GoAffPro',
    'GoDaddy',
    'GoPay',
    'Good Grants',
    'Google Keep',
    'Google+',
    'Gravitec',
    'Greenhouse',
    'Grist',
    'HERE Tracking',
    'HTTP',
    'HacknPlan',
    'Happierleads',
    'HappyFox Chat',
    'Hexomatic',
    'Hexowatch',
    'HeySpace',
    'HireTrack NX',
    'Holded',
    'Hopscotch',
    'Humanitix',
    'IEX Cloud',
    'IP2Proxy',
    'IPEX Helpdesk',
    'IQDial',
    'IQM Reports',
    'ISO',
    'Idiligo',
    'Image',
    'Infor M3',
    'Innform',
    'Interact',
    'Interact.do',
    'Interseller',
    'Invision Community',
    'InvoiceBerry',
    'Invoiced',
    'JSON',
    'JW Player',
    'Jepto',
    'Jibble',
    'JustClick',
    'Kaleyra',
    'Kanban Tool',
    'Kantree',
    'KashFlow',
    'Kizeo Forms',
    'KlickTipp',
    'Klippa',
    'LEAV Engine',
    'Layerise',
    'Lead Agent',
    'LeadSquared',
    'LearnWorlds',
    'Letterdrop',
    'Levity',
    'Lighthouse by Cloudify',
    'Lightspeed eCom',
    'LimbleCMMS',
    'LinkedIn Offline Conversions',
    'Linx Commerce',
    'LiveChat',
    'Lnk.Bio',
    'Logbookie',
    'Lokalise',
    'Loopify',
    'Loqate',
    'Luxafor',
    'MIME',
    'Macanta',
    'Mailkit',
    'Mailmodo',
    'Mailvio',
    'Make',
    'MakeForms',
    'MakePlans',
    'Malcolm!',
    'Mallabe Websites',
    'MangoPay',
    'MantisBT',
    'Markdown',
    'Marketo',
    'Math',
    'Meetime',
    'Meetup Pro',
    'Member Kit',
    'Meraki',
    'Merci Facteur',
    'Metabase',
    'Metatask',
    'Microsoft Dynamics 365 - CRM',
    'Microsoft Power Automate',
    'Mindspun',
    'MobiCRM',
    'Mollie',
    'Moon Invoice',
    'Motionlab',
    'MuleSoft',
    'Mumara',
    'Mural',
    'MyCalendarAlerts',
    'MyCarTracks',
    'Natif.ai',
    'Neaktor',
    'Net0',
    'NetSuite',
    'Neuroflash',
    'NocoDB',
    'Norns AI',
    'Nozbe Teams',
    'OOPSpam Anti-Spam',
    'Omise',
    'Omnivery',
    'OnePageCRM',
    'OpenAI GPT-3',
    'Orday',
    'Outline',
    'Outreach',
    'PLANTA pulse',
    'Paced Email',
    'Paperless.io',
    'Papyrs',
    'Pastebin',
    'Payment Rails',
    'Paystack',
    'PeerBoard',
    'Persat',
    'PersistIQ',
    'Petoffice',
    'Phone number',
    'Pinboard',
    'Pipeliner CRM',
    'Placeholder',
    'Planyo',
    'Porsline',
    'Post My Link',
    'Postalytics',
    'PowerOffice',
    'PracticePanther',
    'Prefinery',
    'Printify',
    'Pro Crew Schedule',
    'Procountor',
    'ProdPad',
    'Product Hunt',
    'ProjectWorks',
    'ProofHub',
    'Pulseem',
    'QuestionPro',
    'QuickChart',
    'Quill Forms',
    'RSS',
    'RWS Language Cloud',
    'Raklet',
    'RapiWha',
    'RapidReg',
    'ReCharge',
    'Redtail CRM',
    'Refiner',
    'RegFox',
    'Rejstříky.info',
    'Rentman',
    'Responder.live',
    'Restdb.io',
    'Restya Core',
    'Retable',
    'Retently',
    'Reverse Contact',
    'ReviewStudio',
    'Revv Documents',
    'Roam-bot',
    'Robly',
    'Robocorp',
    'RocketReach',
    'Ronin',
    'SAP S/4HANA',
    'SFTP',
    'SMSAlert',
    'SMSINDIAHUB',
    'SMSVio',
    'SOAP',
    'SOS Inventory',
    'SSH',
    'Salesmachine',
    'SatisMeter',
    'ScrapeNinja',
    'Scriberr',
    'SeekTable',
    'SegMetrics',
    'SellIntegro CloudPrint',
    'Selly Erp',
    'SendMe',
    'SendX',
    'Sender',
    'Sensorpro',
    'ServiceNow',
    'ServiceWorks',
    'Shippo',
    'Shufflrr',
    'Signaturit',
    'Signority',
    'SimpleCirc',
    'SimpleTix',
    'Simplesat',
    'SimplyBook.me',
    'SimplyMeet.me',
    'Siteglide',
    'SleekFlow',
    'Sling',
    'SmartReach.io',
    'SmartSuite',
    'SmartThings',
    'Smartcat',
    'Smartlook',
    'SnatchBot',
    'Snipcart',
    'Sorry',
    'SpreadsheetWeb Hub',
    'Stannp',
    'Statuspage',
    'Steady',
    'Storeman',
    'Streamlabs',
    'Streamtime',
    'SugarCRM 11',
    'SugarSync',
    'SuperHote',
    'SupportBee',
    'Surveybot',
    'SwiftKanban',
    'Swordfish.ai',
    'TAAPI.IO',
    'Tallyfy',
    'Tars',
    'TeamViewer',
    'Teamgate CRM',
    'Teamwork CRM',
    'Telnyx',
    'Temi',
    'Testomato',
    'Text parser',
    'TextIt',
    'Texting Base',
    'Textlocal',
    'The Bot Platform',
    'Time Doctor',
    'Tisane',
    'Toggl Hire',
    'Toggl Plan',
    'Tolstoy',
    'Tools',
    'Trainual',
    'Trustmary',
    'Twilio Autopilot',
    'UiPath',
    'Umbler uTalk',
    'Units',
    'Uteach',
    'Utilize',
    'Uzeli Salon Software',
    'VERSAT CRM',
    'Vend',
    'Vertex',
    'Vincario VIN Decoder',
    'Virtual Buttons',
    'Vision6',
    'Visma eAccounting',
    'Voxloud',
    'Vxt',
    'Vyte',
    'WEBLUCY™',
    'WP All Import',
    'Wachete',
    'WaiverFile',
    'Weather',
    'Webhooks',
    'Wells Fargo',
    'Whereby',
    'Windy',
    'Wix Answers',
    'Wizishop',
    'Workast',
    'Workday Financial Management',
    'Workday Human Capital Management',
    'Workstack',
    'XML',
    'XMP',
    'Yahoo',
    'Yay! Forms',
    'Yeeflow',
    'Yoast',
    'Yoobic',
    'YouTestMe',
    'Zagomail',
    'Zistemo',
    'Zoho Cliq',
    'Zulip',
    'apaleo',
    'atSpoke',
    'beehiiv',
    'cituro',
    'dlvr.it',
    'eDock',
    'eFileCabinet',
    'easybill',
    'easydoc',
    'iCount',
    'iLert',
    'lc.cx',
    'mWork365',
    'rooom eventCloud',
    'uClassify',
    'ČVUT Grades',
]